repos:
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-json
        exclude: '(^.vscode/|^.aws-sam/|Pipfile.lock)'
      - id: pretty-format-json
        exclude: '(^.vscode/|^.aws-sam/|Pipfile.lock)'
        args:
          - --autofix
          - --indent
          - '2'
      # - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.1
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pycqa/isort
    rev: 5.5.4
    hooks:
      - id: isort
        args: ['--profile', 'black']
